# Generated by Django 2.0.3 on 2018-03-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_auto_20180317_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idvisitante', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField()),
                ('idmenor', models.IntegerField(blank=True, null=True)),
                ('dispositivo', models.IntegerField()),
                ('fechahorainicio', models.DateTimeField(blank=True, null=True)),
                ('fechahorafin', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=5, null=True)),
                ('numeromenores', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('idcama', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('idcama', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('ocupacion', models.PositiveIntegerField()),
                ('disponibilidad', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('iddependencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('cupo', models.PositiveIntegerField(blank=True, null=True)),
                ('menores', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dependencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombrehabitacion', models.CharField(max_length=45)),
                ('piso', models.CharField(max_length=45)),
                ('ncamas', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menor',
            fields=[
                ('idmenor', models.AutoField(db_column='idMenor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'menor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operarios',
            fields=[
                ('idlogin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('identificacion', models.IntegerField()),
                ('privilegio', models.IntegerField()),
                ('usuario', models.CharField(max_length=16)),
                ('contrasena', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'operarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('idtorre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('npisos', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'torre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('idvisitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nummenores', models.PositiveIntegerField(blank=True, db_column='NumMenores', null=True)),
            ],
            options={
                'db_table': 'visitante',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='perfiloperario',
            options={'managed': False},
        ),
    ]
