# Generated by Django 2.0.3 on 2018-03-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_auto_20180317_1713'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfiloperario',
            table='perfiloperario',
        ),
    ]
