# Generated by Django 2.0.3 on 2018-03-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_auto_20180321_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiloperario',
            options={'managed': False},
        ),
    ]
